language: python
python:
  - "3.7"  # Change to a supported version
  - "3.8"
  - "3.9"
before_script:
  - export PYTHONPATH=$PYTHONPATH:$PWD/package 
before_install:
  - sudo apt-get update -y
  - sudo apt-get install python3.7 python3.8 python3.9 python3-pip
install:
  - pip install tabulate
script:
  - python testsuite.py
  - python TestER.py
  - python TestG.py
  - python TestMacro.py
  - python TestWorkout.py
