language: python
python:
  - "3.7"  # Change to a supported version
  - "3.8"
  - "3.9"
before_script:
  - export PYTHONPATH=$PYTHONPATH:$PWD/package 
install:
  - pip install tabulate
script:
  - python testsuite.py
  - python TestER.py
  - python TestG.py
  - python TestMacro.py
  - python TestWorkout.py
